--SQL file
Comandos pa meter info en SQL:

INSERT INTO MEDICO_ENTITY (ID, NOMBRE) VALUES (100, 'Fernanda Gomez');

INSERT INTO MEDICO_ENTITY (ID, NOMBRE) VALUES (101, 'Fernando Gomez');


INSERT INTO MEDICO_ENTITY (ID ,APELLIDO,ESPECIALIDAD,NOMBRE,REGISTROMEDICO) VALUES (102, 'POS GOMEZ', 'COMER', 'Fernando Gomez', 'NO LO SE');


Pa ver tabla:


SELECT * FROM MEDICO_ENTITY;